package kr.co.dwebss.kococo.core.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.hateoas.ResourceSupport;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AnalysisDetails generated by hbm2java
 */
@Entity
@Table(name = "analysis_details", catalog = "kococo")
public class AnalysisDetails extends ResourceSupport implements java.io.Serializable {
	
	private Integer analysisId;
	private Integer analysisDetailsId;
	private Analysis analysis;
	private Integer termTypeCd;
	@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
	private LocalDateTime termStartDt;
	@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
	private LocalDateTime termEndDt;
	private String analysisData;

	public AnalysisDetails() {
	}

	public AnalysisDetails(int termTypeCd, LocalDateTime termStartDt, LocalDateTime termEndDt) {
		this.termTypeCd = termTypeCd;
		this.termStartDt = termStartDt;
		this.termEndDt = termEndDt;
	}

	public AnalysisDetails(Analysis analysis, Integer termTypeCd, LocalDateTime termStartDt, LocalDateTime termEndDt ,String analysisData) {
		this.analysis = analysis;
		this.termTypeCd = termTypeCd;
		this.termStartDt = termStartDt;
		this.termEndDt = termEndDt;
		this.analysisData = analysisData;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ANALYSIS_DETAILS_ID", unique = true, nullable = false)
	public Integer getAnalysisDetailsId() {
		return this.analysisDetailsId;
	}

	public void setAnalysisDetailsId(Integer analysisDetailsId) {
		this.analysisDetailsId = analysisDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@JoinColumn(name = "ANALYSIS_ID")
	public Analysis getAnalysis() {
		return this.analysis;
	}

	public void setAnalysis(Analysis analysis) {
		this.analysis = analysis;
	}

	@Column(name = "ANALYSIS_ID", insertable = false, updatable = false)
	public Integer getAnalysisId() {
		return this.analysisId;
	}

	public void setAnalysisId(Integer analysisId) {
		this.analysisId = analysisId;
	}

	@Column(name = "TERM_TYPE_CD")
	public Integer getTermTypeCd() {
		return this.termTypeCd;
	}

	public void setTermTypeCd(Integer termTypeCd) {
		this.termTypeCd = termTypeCd;
	}

	@Column(name = "TERM_START_DT", length = 19)
	public LocalDateTime getTermStartDt() {
		return this.termStartDt;
	}

	public void setTermStartDt(LocalDateTime termStartDt) {
		this.termStartDt = termStartDt;
	}

	@Column(name = "TERM_END_DT", length = 19)
	public LocalDateTime getTermEndDt() {
		return this.termEndDt;
	}

	public void setTermEndDt(LocalDateTime termEndDt) {
		this.termEndDt = termEndDt;
	}

	@Column(name = "ANALYSIS_DATA")
	public String getAnalysisData() {
		return analysisData;
	}

	public void setAnalysisData(String analysisData) {
		this.analysisData = analysisData;
	}

}
