package kr.co.dwebss.kococo.core.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.hateoas.ResourceSupport;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AnalysisDetails generated by hbm2java
 */
@Entity
@Table(name = "analysis_details", catalog = "kococo")
public class AnalysisDetails extends ResourceSupport implements java.io.Serializable {
	
	private Integer analysisId;
	private Integer analysisDetailsId;
	private Analysis analysis;
	private Integer termTypeCd;
	@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
	private LocalDateTime termStartDt;
	@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
	private LocalDateTime termEndDt;
	private Character claimYn='N';
	private Integer claimReasonCd;
	private String claimContents;
	@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
	private LocalDateTime claimRegistDt;

	public AnalysisDetails() {
	}

	public AnalysisDetails(int termTypeCd, LocalDateTime termStartDt, LocalDateTime termEndDt) {
		this.termTypeCd = termTypeCd;
		this.termStartDt = termStartDt;
		this.termEndDt = termEndDt;
	}

	public AnalysisDetails(Analysis analysis, Integer termTypeCd, LocalDateTime termStartDt, LocalDateTime termEndDt ,Character claimYn, Integer claimReasonCd,
			String claimContents, LocalDateTime claimRegistDt) {
		this.analysis = analysis;
		this.termTypeCd = termTypeCd;
		this.termStartDt = termStartDt;
		this.termEndDt = termEndDt;
		this.claimYn = claimYn;
		this.claimReasonCd = claimReasonCd;
		this.claimContents = claimContents;
		this.claimRegistDt = claimRegistDt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ANALYSIS_DETAILS_ID", unique = true, nullable = false)
	public Integer getAnalysisDetailsId() {
		return this.analysisDetailsId;
	}

	public void setAnalysisDetailsId(Integer analysisDetailsId) {
		this.analysisDetailsId = analysisDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@JoinColumn(name = "ANALYSIS_ID")
	public Analysis getAnalysis() {
		return this.analysis;
	}

	public void setAnalysis(Analysis analysis) {
		this.analysis = analysis;
	}

	@Column(name = "ANALYSIS_ID", insertable = false, updatable = false)
	public Integer getAnalysisId() {
		return this.analysisId;
	}

	public void setAnalysisId(Integer analysisId) {
		this.analysisId = analysisId;
	}

	@Column(name = "TERM_TYPE_CD")
	public Integer getTermTypeCd() {
		return this.termTypeCd;
	}

	public void setTermTypeCd(Integer termTypeCd) {
		this.termTypeCd = termTypeCd;
	}

	@Column(name = "TERM_START_DT", length = 19)
	public LocalDateTime getTermStartDt() {
		return this.termStartDt;
	}

	public void setTermStartDt(LocalDateTime termStartDt) {
		this.termStartDt = termStartDt;
	}

	@Column(name = "TERM_END_DT", length = 19)
	public LocalDateTime getTermEndDt() {
		return this.termEndDt;
	}

	public void setTermEndDt(LocalDateTime termEndDt) {
		this.termEndDt = termEndDt;
	}

	@Column(name = "CLAIM_YN", length = 1)
	public Character getClaimYn() {
		return this.claimYn;
	}

	public void setClaimYn(Character claimYn) {
		this.claimYn = claimYn;
	}

	@Column(name = "CLAIM_REASON_CD")
	public Integer getClaimReasonCd() {
		return this.claimReasonCd;
	}

	public void setClaimReasonCd(Integer claimReasonCd) {
		this.claimReasonCd = claimReasonCd;
	}

	@Column(name = "CLAIM_CONTENTS", length = 250)
	public String getClaimContents() {
		return this.claimContents;
	}

	public void setClaimContents(String claimContents) {
		this.claimContents = claimContents;
	}

	@Column(name = "CLAIM_REGIST_DT", length = 19)
	public LocalDateTime getClaimRegistDt() {
		return this.claimRegistDt;
	}

	public void setClaimRegistDt(LocalDateTime claimRegistDt) {
		this.claimRegistDt = claimRegistDt;
	}
}
