package kr.co.dwebss.kococo.core.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.hateoas.ResourceSupport;

/**
 * Code generated by hbm2java
 */
@Entity
@Table(name = "code", catalog = "kococo")
public class Code extends ResourceSupport implements java.io.Serializable {

	private int code;
	private String codeCateogry;
	private String codeValue;
	private String codeDisplayValue;

	public Code() {
	}

	public Code(int code) {
		this.code = code;
	}


	public Code(int code, String codeCateogry, String codeValue, String codeDisplayValue) {
		super();
		this.code = code;
		this.codeCateogry = codeCateogry;
		this.codeValue = codeValue;
		this.codeDisplayValue = codeDisplayValue;
	}

	@Id

	@Column(name = "CODE", unique = true, nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	@Column(name = "CODE_CATEOGRY", length = 10)
	public String getCodeCateogry() {
		return this.codeCateogry;
	}

	public void setCodeCateogry(String codeCateogry) {
		this.codeCateogry = codeCateogry;
	}

	@Column(name = "CODE_VALUE", length = 10)
	public String getCodeValue() {
		return this.codeValue;
	}

	public void setCodeValue(String codeValue) {
		this.codeValue = codeValue;
	}

	@Column(name = "CODE_DISPLAY_VALUE", length = 30)
	public String getCodeDisplayValue() {
		return codeDisplayValue;
	}

	public void setCodeDisplayValue(String codeDisplayValue) {
		this.codeDisplayValue = codeDisplayValue;
	}

}
