package kr.co.dwebss.kococo.core.entities;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ConsultingReply generated by hbm2java
 */
@Entity
@Table(name = "consulting_reply", catalog = "kococo_dev")
public class ConsultingReply implements java.io.Serializable {

	private int consultingReplyId;
	private int consultingId;
	private Consulting consulting;
	private String consultingReplyContents;
	private Date consultingReplyRegistDt;
	private String consultingReplyUserId;

	public ConsultingReply() {
	}

	public ConsultingReply(int consultingReplyId) {
		this.consultingReplyId = consultingReplyId;
	}

	public ConsultingReply(int consultingReplyId, Consulting consulting, String consultingReplyContents,
			Date consultingReplyRegistDt, String consultingReplyUserId) {
		this.consultingReplyId = consultingReplyId;
		this.consulting = consulting;
		this.consultingReplyContents = consultingReplyContents;
		this.consultingReplyRegistDt = consultingReplyRegistDt;
		this.consultingReplyUserId = consultingReplyUserId;
	}

	@Id

	@Column(name = "CONSULTING_REPLY_ID", unique = true, nullable = false)
	public int getConsultingReplyId() {
		return this.consultingReplyId;
	}

	public void setConsultingReplyId(int consultingReplyId) {
		this.consultingReplyId = consultingReplyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@JoinColumn(name = "CONSULTING_ID")
	public Consulting getConsulting() {
		return this.consulting;
	}

	public void setConsulting(Consulting consulting) {
		this.consulting = consulting;
	}

	@Column(name = "CONSULTING_REPLY_CONTENTS", length = 5000)
	public String getConsultingReplyContents() {
		return this.consultingReplyContents;
	}

	public void setConsultingReplyContents(String consultingReplyContents) {
		this.consultingReplyContents = consultingReplyContents;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CONSULTING_REPLY_REGIST_DT", length = 19)
	public Date getConsultingReplyRegistDt() {
		return this.consultingReplyRegistDt;
	}

	@Column(name = "CONSULTING_ID", insertable = false, updatable = false)
	public Integer getConsultingId() {
		return this.consultingId;
	}

	public void setConsultingId(Integer consultingId) {
		this.consultingId = consultingId;
	}

	public void setConsultingReplyRegistDt(Date consultingReplyRegistDt) {
		this.consultingReplyRegistDt = consultingReplyRegistDt;
	}

	@Column(name = "CONSULTING_REPLY_USER_ID", length = 36)
	public String getConsultingReplyUserId() {
		return this.consultingReplyUserId;
	}

	public void setConsultingReplyUserId(String consultingReplyUserId) {
		this.consultingReplyUserId = consultingReplyUserId;
	}

}
