package kr.co.dwebss.kococo.core.entities;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "kococo")
public class Payment implements java.io.Serializable {

	private String userAppId;
	private int paymentId;
	private User user;
	private int paymentStatus;
	private String paymentOrderId;
	private String paymentPurchaseToken;
	private String paymentDeveloperPayload;
	private Date paymentDt;
	private Date paymentCancelDt;

	public Payment() {
	}

	public Payment(int paymentId, String userAppId, int paymentStatus, String paymentOrderId, String paymentPurchaseToken,
			String paymentDeveloperPayload, Date paymentDt) {
		this.paymentId = paymentId;
		this.userAppId = userAppId;
		this.paymentStatus = paymentStatus;
		this.paymentOrderId = paymentOrderId;
		this.paymentPurchaseToken = paymentPurchaseToken;
		this.paymentDeveloperPayload = paymentDeveloperPayload;
		this.paymentDt = paymentDt;
	}
	
	public Payment(int paymentId, User user, int paymentStatus, String paymentOrderId, String paymentPurchaseToken,
			String paymentDeveloperPayload, Date paymentDt) {
		this.paymentId = paymentId;
		this.user = user;
		this.paymentStatus = paymentStatus;
		this.paymentOrderId = paymentOrderId;
		this.paymentPurchaseToken = paymentPurchaseToken;
		this.paymentDeveloperPayload = paymentDeveloperPayload;
		this.paymentDt = paymentDt;
	}

	public Payment(int paymentId, User user, int paymentStatus, String paymentOrderId, String paymentPurchaseToken,
			String paymentDeveloperPayload, Date paymentDt, Date paymentCancelDt) {
		this.paymentId = paymentId;
		this.user = user;
		this.paymentStatus = paymentStatus;
		this.paymentOrderId = paymentOrderId;
		this.paymentPurchaseToken = paymentPurchaseToken;
		this.paymentDeveloperPayload = paymentDeveloperPayload;
		this.paymentDt = paymentDt;
		this.paymentCancelDt = paymentCancelDt;
	}

	@Id

	@Column(name = "PAYMENT_ID", unique = true, nullable = false)
	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "USER_APP_ID", length = 36)
	public String getUserAppId() {
		return this.userAppId;
	}

	public void setUserAppId(String userAppId) {
		this.userAppId = userAppId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USER_APP_ID", insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "PAYMENT_STATUS", nullable = false)
	public int getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(int paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	@Column(name = "PAYMENT_ORDER_ID", nullable = false, length = 1000)
	public String getPaymentOrderId() {
		return this.paymentOrderId;
	}

	public void setPaymentOrderId(String paymentOrderId) {
		this.paymentOrderId = paymentOrderId;
	}

	@Column(name = "PAYMENT_PURCHASE_TOKEN", nullable = false, length = 1000)
	public String getPaymentPurchaseToken() {
		return this.paymentPurchaseToken;
	}

	public void setPaymentPurchaseToken(String paymentPurchaseToken) {
		this.paymentPurchaseToken = paymentPurchaseToken;
	}

	@Column(name = "PAYMENT_DEVELOPER_PAYLOAD", nullable = false, length = 1000)
	public String getPaymentDeveloperPayload() {
		return this.paymentDeveloperPayload;
	}

	public void setPaymentDeveloperPayload(String paymentDeveloperPayload) {
		this.paymentDeveloperPayload = paymentDeveloperPayload;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PAYMENT_DT", nullable = false, length = 19)
	public Date getPaymentDt() {
		return this.paymentDt;
	}

	public void setPaymentDt(Date paymentDt) {
		this.paymentDt = paymentDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PAYMENT_CANCEL_DT", length = 19)
	public Date getPaymentCancelDt() {
		return this.paymentCancelDt;
	}

	public void setPaymentCancelDt(Date paymentCancelDt) {
		this.paymentCancelDt = paymentCancelDt;
	}

}
