package kr.co.dwebss.kococo.core.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.hateoas.ResourceSupport;

/**
 * Record generated by hbm2java
 */
@Entity
@Table(name = "record", catalog = "kococo")
public class RecordOnly extends ResourceSupport implements java.io.Serializable {

	private String userAppId;
	private Integer recordId;
	private Admin admin;
	private User user;
	@DateTimeFormat(pattern = "yyyy-MM-dd'T'")
	private LocalDate recordStartD;
	@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
	private LocalDateTime recordStartDt;
	@DateTimeFormat(pattern = "yyyy-MM-dd'T'")
	private LocalDate recordEndD;
	@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
	private LocalDateTime recordEndDt;
	private Character consultingYn='N';
	private Character consultingReplyYn='N';
	private String consultingTitle;
	private String consultingContents;
	@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
	private LocalDateTime consultingRegistDt;
	private String consultingReplyContents;
	@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
	private LocalDateTime consultingReplyRegistDt;
	private Code sleepStatusCd;
	private Integer sleepStatusCdId;
	
	public RecordOnly() {
	}

	public RecordOnly(Admin admin, String userAppId, LocalDateTime recordStartDt, LocalDateTime recordEndDt) {
		this.admin = admin;
		this.userAppId = userAppId;
		this.recordStartDt = recordStartDt;
		this.recordEndDt = recordEndDt;
	}
	
	public RecordOnly(Admin admin, User user, LocalDate recordStartD, LocalDateTime recordStartDt, LocalDate recordEndD, LocalDateTime recordEndDt,
			Character consultingYn, Character consultingReplyYn, String consultingTitle, String consultingContents,
			LocalDateTime consultingRegistDt, String consultingReplyContents, LocalDateTime consultingReplyRegistDt,
			Code sleepStatusCd) {
		this.admin = admin;
		this.user = user;
		this.recordStartD = recordStartD;
		this.recordStartDt = recordStartDt;
		this.recordEndD = recordEndD;
		this.recordEndDt = recordEndDt;
		this.consultingYn = consultingYn;
		this.consultingReplyYn = consultingReplyYn;
		this.consultingTitle = consultingTitle;
		this.consultingContents = consultingContents;
		this.consultingRegistDt = consultingRegistDt;
		this.consultingReplyContents = consultingReplyContents;
		this.consultingReplyRegistDt = consultingReplyRegistDt;
		this.sleepStatusCd = sleepStatusCd;
	}


	public RecordOnly(String consultingTitle, String consultingContents, int recordId) {
		this.recordId = recordId;
		this.consultingTitle = consultingTitle;
		this.consultingContents = consultingContents;
	}


	public RecordOnly(Character consultingYn, int recordId) {
		this.recordId = recordId;
		this.consultingYn = consultingYn;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RECORD_ID", unique = true, nullable = false)
	public Integer getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}


	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SLEEP_STATUS_CD", insertable = false, updatable = false)
	public Code getSleepStatusCd() {
		return this.sleepStatusCd;
	}

	public void setSleepStatusCd(Code sleepStatusCd) {
		this.sleepStatusCd = sleepStatusCd;
	}

	@Column(name = "SLEEP_STATUS_CD", length = 11)
	public Integer getSleepStatusCdId() {
		return this.sleepStatusCdId;
	}

	public void setSleepStatusCdId(Integer sleepStatusCdId) {
		this.sleepStatusCdId = sleepStatusCdId;
	}

	@Column(name = "USER_APP_ID", length = 36)
	public String getUserAppId() {
		return this.userAppId;
	}

	public void setUserAppId(String userAppId) {
		this.userAppId = userAppId;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CONSULTING_REPLY_ADMIN_ID")
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USER_APP_ID", insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "RECORD_START_D", length = 10)
	public LocalDate getRecordStartD() {
		if(this.recordStartD==null&&this.recordStartDt!=null) {
			this.recordStartD = this.recordStartDt.toLocalDate();
		}
		return this.recordStartD;
	}

	public void setRecordStartD(LocalDate recordStartD) {
		this.recordStartD = recordStartD;
	}

	@Column(name = "RECORD_START_DT", length = 19)
	public LocalDateTime getRecordStartDt() {
		return this.recordStartDt;
	}

	public void setRecordStartDt(LocalDateTime recordStartDt) {
		this.recordStartDt = recordStartDt;
	}

	@Column(name = "RECORD_END_D", length = 10)
	public LocalDate getRecordEndD() {
		if(this.recordEndD==null&&this.recordEndDt!=null) {
			this.recordEndD = this.recordEndDt.toLocalDate();
		}
		return this.recordEndD;
	}

	public void setRecordEndD(LocalDate recordEndD) {
		this.recordEndD = recordEndD;
	}

	@Column(name = "RECORD_END_DT", length = 19)
	public LocalDateTime getRecordEndDt() {
		return this.recordEndDt;
	}

	public void setRecordEndDt(LocalDateTime recordEndDt) {
		this.recordEndDt = recordEndDt;
	}

	@Column(name = "CONSULTING_YN", length = 1)
	public Character getConsultingYn() {
		return this.consultingYn;
	}

	public void setConsultingYn(Character consultingYn) {
		this.consultingYn = consultingYn;
	}

	@Column(name = "CONSULTING_REPLY_YN", length = 1)
	public Character getConsultingReplyYn() {
		return this.consultingReplyYn;
	}

	public void setConsultingReplyYn(Character consultingReplyYn) {
		this.consultingReplyYn = consultingReplyYn;
	}

	@Column(name = "CONSULTING_TITLE", length = 10)
	public String getConsultingTitle() {
		return this.consultingTitle;
	}

	public void setConsultingTitle(String consultingTitle) {
		this.consultingTitle = consultingTitle;
	}

	@Column(name = "CONSULTING_CONTENTS", length = 250)
	public String getConsultingContents() {
		return this.consultingContents;
	}

	public void setConsultingContents(String consultingContents) {
		this.consultingContents = consultingContents;
	}

	@Column(name = "CONSULTING_REGIST_DT", length = 19)
	public LocalDateTime getConsultingRegistDt() {
		if(this.consultingRegistDt == null && this.consultingTitle != null && this.consultingContents!=null) {
			return LocalDateTime.now();
		}else {
			return this.consultingRegistDt;
		}
	}

	public void setConsultingRegistDt(LocalDateTime consultingRegistDt) {
		if(this.consultingRegistDt == null && this.consultingTitle != null && this.consultingContents!=null) {
			this.consultingRegistDt = LocalDateTime.now();
		}else {
			this.consultingRegistDt = consultingRegistDt;
		}
	}

	@Column(name = "CONSULTING_REPLY_CONTENTS", length = 250)
	public String getConsultingReplyContents() {
		return this.consultingReplyContents;
	}

	public void setConsultingReplyContents(String consultingReplyContents) {
		this.consultingReplyContents = consultingReplyContents;
	}

	@Column(name = "CONSULTING_REPLY_REGIST_DT", length = 19)
	public LocalDateTime getConsultingReplyRegistDt() {
		return this.consultingReplyRegistDt;
	}

	public void setConsultingReplyRegistDt(LocalDateTime consultingReplyRegistDt) {
		this.consultingReplyRegistDt = consultingReplyRegistDt;
	}
}
