package kr.co.dwebss.kococo.core.entities;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserTicketHistory generated by hbm2java
 */
@Entity
@Table(name = "user_ticket_history", catalog = "kococo_dev")
public class UserTicketHistory implements java.io.Serializable {

	private int userTicketHistoryId;
	private String userAppId;
	private Integer consultingId;
	private Integer paymentId;
	private int userTicketCnt;
	private Date userTicketHistoryDt;

	public UserTicketHistory() {
	}

	public UserTicketHistory(int userTicketHistoryId, int userTicketCnt, Date userTicketHistoryDt) {
		this.userTicketHistoryId = userTicketHistoryId;
		this.userTicketCnt = userTicketCnt;
		this.userTicketHistoryDt = userTicketHistoryDt;
	}

	public UserTicketHistory(int userTicketHistoryId, String userAppId, Integer consultingId, Integer paymentId,
			int userTicketCnt, Date userTicketHistoryDt) {
		this.userTicketHistoryId = userTicketHistoryId;
		this.userAppId = userAppId;
		this.consultingId = consultingId;
		this.paymentId = paymentId;
		this.userTicketCnt = userTicketCnt;
		this.userTicketHistoryDt = userTicketHistoryDt;
	}

	@Id

	@Column(name = "USER_TICKET_HISTORY_ID", unique = true, nullable = false)
	public int getUserTicketHistoryId() {
		return this.userTicketHistoryId;
	}

	public void setUserTicketHistoryId(int userTicketHistoryId) {
		this.userTicketHistoryId = userTicketHistoryId;
	}

	@Column(name = "USER_APP_ID", length = 36)
	public String getUserAppId() {
		return this.userAppId;
	}

	public void setUserAppId(String userAppId) {
		this.userAppId = userAppId;
	}

	@Column(name = "CONSULTING_ID")
	public Integer getConsultingId() {
		return this.consultingId;
	}

	public void setConsultingId(Integer consultingId) {
		this.consultingId = consultingId;
	}

	@Column(name = "PAYMENT_ID")
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "USER_TICKET_CNT", nullable = false)
	public int getUserTicketCnt() {
		return this.userTicketCnt;
	}

	public void setUserTicketCnt(int userTicketCnt) {
		this.userTicketCnt = userTicketCnt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USER_TICKET_HISTORY_DT", nullable = false, length = 19)
	public Date getUserTicketHistoryDt() {
		return this.userTicketHistoryDt;
	}

	public void setUserTicketHistoryDt(Date userTicketHistoryDt) {
		this.userTicketHistoryDt = userTicketHistoryDt;
	}

}
